name: CI linting and testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e ".[cpu,dev]"
    - name: Test with pytest
      run: |
        make test PYTHON_VERSION=${{ matrix.python-version }}
    - name: Lint
      run: |
        make lint
